// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

import 'api/dart/api.dart';
import 'frb_generated.dart';
import 'media.dart';
import 'media/constraints.dart';
import 'media/track.dart';
import 'media/track/remote.dart';
import 'room.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ConnectionHandlePtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_ConnectionHandlePtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_JasonPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_JasonPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_LocalMediaTrackPtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_LocalMediaTrackPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_MediaManagerHandlePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_MediaManagerHandlePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ReconnectHandlePtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_ReconnectHandlePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_RemoteMediaTrackPtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_RemoteMediaTrackPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RoomHandlePtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_RoomHandlePtr;

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  ConnectionHandle dco_decode_RustOpaque_ConnectionHandle(dynamic raw);

  @protected
  Jason dco_decode_RustOpaque_Jason(dynamic raw);

  @protected
  LocalMediaTrack dco_decode_RustOpaque_LocalMediaTrack(dynamic raw);

  @protected
  MediaManagerHandle dco_decode_RustOpaque_MediaManagerHandle(dynamic raw);

  @protected
  ReconnectHandle dco_decode_RustOpaque_ReconnectHandle(dynamic raw);

  @protected
  RemoteMediaTrack dco_decode_RustOpaque_RemoteMediaTrack(dynamic raw);

  @protected
  RoomHandle dco_decode_RustOpaque_RoomHandle(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApiAudioConstraints dco_decode_api_audio_constraints(dynamic raw);

  @protected
  ApiConstrainFacingMode dco_decode_api_constrain_facing_mode(dynamic raw);

  @protected
  ApiDeviceVideoTrackConstraints dco_decode_api_device_video_track_constraints(
      dynamic raw);

  @protected
  ApiDisplayVideoTrackConstraints
      dco_decode_api_display_video_track_constraints(dynamic raw);

  @protected
  ApiMediaDeviceDetails dco_decode_api_media_device_details(dynamic raw);

  @protected
  ApiMediaDisplayDetails dco_decode_api_media_display_details(dynamic raw);

  @protected
  ApiMediaStreamSettings dco_decode_api_media_stream_settings(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ApiAudioConstraints dco_decode_box_autoadd_api_audio_constraints(dynamic raw);

  @protected
  ApiConstrainFacingMode dco_decode_box_autoadd_api_constrain_facing_mode(
      dynamic raw);

  @protected
  ApiDeviceVideoTrackConstraints
      dco_decode_box_autoadd_api_device_video_track_constraints(dynamic raw);

  @protected
  ApiDisplayVideoTrackConstraints
      dco_decode_box_autoadd_api_display_video_track_constraints(dynamic raw);

  @protected
  ApiMediaStreamSettings dco_decode_box_autoadd_api_media_stream_settings(
      dynamic raw);

  @protected
  ConstrainBoolean dco_decode_box_autoadd_constrain_boolean(dynamic raw);

  @protected
  ConstrainU32 dco_decode_box_autoadd_constrain_u_32(dynamic raw);

  @protected
  MediaSourceKind dco_decode_box_autoadd_media_source_kind(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ConstrainBoolean dco_decode_constrain_boolean(dynamic raw);

  @protected
  ConstrainU32 dco_decode_constrain_u_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FacingMode dco_decode_facing_mode(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<LocalMediaTrack> dco_decode_list_RustOpaque_LocalMediaTrack(dynamic raw);

  @protected
  List<ApiMediaDeviceDetails> dco_decode_list_api_media_device_details(
      dynamic raw);

  @protected
  List<ApiMediaDisplayDetails> dco_decode_list_api_media_display_details(
      dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MediaDeviceKind dco_decode_media_device_kind(dynamic raw);

  @protected
  MediaDirection dco_decode_media_direction(dynamic raw);

  @protected
  MediaKind dco_decode_media_kind(dynamic raw);

  @protected
  MediaSourceKind dco_decode_media_source_kind(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ApiAudioConstraints? dco_decode_opt_box_autoadd_api_audio_constraints(
      dynamic raw);

  @protected
  ApiConstrainFacingMode? dco_decode_opt_box_autoadd_api_constrain_facing_mode(
      dynamic raw);

  @protected
  ApiDeviceVideoTrackConstraints?
      dco_decode_opt_box_autoadd_api_device_video_track_constraints(
          dynamic raw);

  @protected
  ApiDisplayVideoTrackConstraints?
      dco_decode_opt_box_autoadd_api_display_video_track_constraints(
          dynamic raw);

  @protected
  ConstrainBoolean? dco_decode_opt_box_autoadd_constrain_boolean(dynamic raw);

  @protected
  ConstrainU32? dco_decode_opt_box_autoadd_constrain_u_32(dynamic raw);

  @protected
  MediaSourceKind? dco_decode_opt_box_autoadd_media_source_kind(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  RoomCloseReason dco_decode_room_close_reason(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  ConnectionHandle sse_decode_RustOpaque_ConnectionHandle(
      SseDeserializer deserializer);

  @protected
  Jason sse_decode_RustOpaque_Jason(SseDeserializer deserializer);

  @protected
  LocalMediaTrack sse_decode_RustOpaque_LocalMediaTrack(
      SseDeserializer deserializer);

  @protected
  MediaManagerHandle sse_decode_RustOpaque_MediaManagerHandle(
      SseDeserializer deserializer);

  @protected
  ReconnectHandle sse_decode_RustOpaque_ReconnectHandle(
      SseDeserializer deserializer);

  @protected
  RemoteMediaTrack sse_decode_RustOpaque_RemoteMediaTrack(
      SseDeserializer deserializer);

  @protected
  RoomHandle sse_decode_RustOpaque_RoomHandle(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApiAudioConstraints sse_decode_api_audio_constraints(
      SseDeserializer deserializer);

  @protected
  ApiConstrainFacingMode sse_decode_api_constrain_facing_mode(
      SseDeserializer deserializer);

  @protected
  ApiDeviceVideoTrackConstraints sse_decode_api_device_video_track_constraints(
      SseDeserializer deserializer);

  @protected
  ApiDisplayVideoTrackConstraints
      sse_decode_api_display_video_track_constraints(
          SseDeserializer deserializer);

  @protected
  ApiMediaDeviceDetails sse_decode_api_media_device_details(
      SseDeserializer deserializer);

  @protected
  ApiMediaDisplayDetails sse_decode_api_media_display_details(
      SseDeserializer deserializer);

  @protected
  ApiMediaStreamSettings sse_decode_api_media_stream_settings(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ApiAudioConstraints sse_decode_box_autoadd_api_audio_constraints(
      SseDeserializer deserializer);

  @protected
  ApiConstrainFacingMode sse_decode_box_autoadd_api_constrain_facing_mode(
      SseDeserializer deserializer);

  @protected
  ApiDeviceVideoTrackConstraints
      sse_decode_box_autoadd_api_device_video_track_constraints(
          SseDeserializer deserializer);

  @protected
  ApiDisplayVideoTrackConstraints
      sse_decode_box_autoadd_api_display_video_track_constraints(
          SseDeserializer deserializer);

  @protected
  ApiMediaStreamSettings sse_decode_box_autoadd_api_media_stream_settings(
      SseDeserializer deserializer);

  @protected
  ConstrainBoolean sse_decode_box_autoadd_constrain_boolean(
      SseDeserializer deserializer);

  @protected
  ConstrainU32 sse_decode_box_autoadd_constrain_u_32(
      SseDeserializer deserializer);

  @protected
  MediaSourceKind sse_decode_box_autoadd_media_source_kind(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ConstrainBoolean sse_decode_constrain_boolean(SseDeserializer deserializer);

  @protected
  ConstrainU32 sse_decode_constrain_u_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FacingMode sse_decode_facing_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<LocalMediaTrack> sse_decode_list_RustOpaque_LocalMediaTrack(
      SseDeserializer deserializer);

  @protected
  List<ApiMediaDeviceDetails> sse_decode_list_api_media_device_details(
      SseDeserializer deserializer);

  @protected
  List<ApiMediaDisplayDetails> sse_decode_list_api_media_display_details(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MediaDeviceKind sse_decode_media_device_kind(SseDeserializer deserializer);

  @protected
  MediaDirection sse_decode_media_direction(SseDeserializer deserializer);

  @protected
  MediaKind sse_decode_media_kind(SseDeserializer deserializer);

  @protected
  MediaSourceKind sse_decode_media_source_kind(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ApiAudioConstraints? sse_decode_opt_box_autoadd_api_audio_constraints(
      SseDeserializer deserializer);

  @protected
  ApiConstrainFacingMode? sse_decode_opt_box_autoadd_api_constrain_facing_mode(
      SseDeserializer deserializer);

  @protected
  ApiDeviceVideoTrackConstraints?
      sse_decode_opt_box_autoadd_api_device_video_track_constraints(
          SseDeserializer deserializer);

  @protected
  ApiDisplayVideoTrackConstraints?
      sse_decode_opt_box_autoadd_api_display_video_track_constraints(
          SseDeserializer deserializer);

  @protected
  ConstrainBoolean? sse_decode_opt_box_autoadd_constrain_boolean(
      SseDeserializer deserializer);

  @protected
  ConstrainU32? sse_decode_opt_box_autoadd_constrain_u_32(
      SseDeserializer deserializer);

  @protected
  MediaSourceKind? sse_decode_opt_box_autoadd_media_source_kind(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  RoomCloseReason sse_decode_room_close_reason(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_ConnectionHandle(
      ConnectionHandle self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_Jason(Jason self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_LocalMediaTrack(
      LocalMediaTrack self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_MediaManagerHandle(
      MediaManagerHandle self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_ReconnectHandle(
      ReconnectHandle self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_RemoteMediaTrack(
      RemoteMediaTrack self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_RoomHandle(
      RoomHandle self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_api_audio_constraints(
      ApiAudioConstraints self, SseSerializer serializer);

  @protected
  void sse_encode_api_constrain_facing_mode(
      ApiConstrainFacingMode self, SseSerializer serializer);

  @protected
  void sse_encode_api_device_video_track_constraints(
      ApiDeviceVideoTrackConstraints self, SseSerializer serializer);

  @protected
  void sse_encode_api_display_video_track_constraints(
      ApiDisplayVideoTrackConstraints self, SseSerializer serializer);

  @protected
  void sse_encode_api_media_device_details(
      ApiMediaDeviceDetails self, SseSerializer serializer);

  @protected
  void sse_encode_api_media_display_details(
      ApiMediaDisplayDetails self, SseSerializer serializer);

  @protected
  void sse_encode_api_media_stream_settings(
      ApiMediaStreamSettings self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_audio_constraints(
      ApiAudioConstraints self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_constrain_facing_mode(
      ApiConstrainFacingMode self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_device_video_track_constraints(
      ApiDeviceVideoTrackConstraints self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_display_video_track_constraints(
      ApiDisplayVideoTrackConstraints self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_media_stream_settings(
      ApiMediaStreamSettings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_constrain_boolean(
      ConstrainBoolean self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_constrain_u_32(
      ConstrainU32 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_source_kind(
      MediaSourceKind self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_constrain_boolean(
      ConstrainBoolean self, SseSerializer serializer);

  @protected
  void sse_encode_constrain_u_32(ConstrainU32 self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_facing_mode(FacingMode self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_RustOpaque_LocalMediaTrack(
      List<LocalMediaTrack> self, SseSerializer serializer);

  @protected
  void sse_encode_list_api_media_device_details(
      List<ApiMediaDeviceDetails> self, SseSerializer serializer);

  @protected
  void sse_encode_list_api_media_display_details(
      List<ApiMediaDisplayDetails> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_media_device_kind(
      MediaDeviceKind self, SseSerializer serializer);

  @protected
  void sse_encode_media_direction(
      MediaDirection self, SseSerializer serializer);

  @protected
  void sse_encode_media_kind(MediaKind self, SseSerializer serializer);

  @protected
  void sse_encode_media_source_kind(
      MediaSourceKind self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_api_audio_constraints(
      ApiAudioConstraints? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_api_constrain_facing_mode(
      ApiConstrainFacingMode? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_api_device_video_track_constraints(
      ApiDeviceVideoTrackConstraints? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_api_display_video_track_constraints(
      ApiDisplayVideoTrackConstraints? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_constrain_boolean(
      ConstrainBoolean? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_constrain_u_32(
      ConstrainU32? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_media_source_kind(
      MediaSourceKind? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_room_close_reason(
      RoomCloseReason self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void rust_arc_increment_strong_count_RustOpaque_ConnectionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_ConnectionHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_ConnectionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_ConnectionHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_ConnectionHandle =
      _rust_arc_increment_strong_count_RustOpaque_ConnectionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_ConnectionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_ConnectionHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_ConnectionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_ConnectionHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_ConnectionHandle =
      _rust_arc_decrement_strong_count_RustOpaque_ConnectionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_Jason(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_Jason(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_JasonPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
      'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_Jason');
  late final _rust_arc_increment_strong_count_RustOpaque_Jason =
      _rust_arc_increment_strong_count_RustOpaque_JasonPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_Jason(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_Jason(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_JasonPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
      'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_Jason');
  late final _rust_arc_decrement_strong_count_RustOpaque_Jason =
      _rust_arc_decrement_strong_count_RustOpaque_JasonPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_LocalMediaTrack(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_LocalMediaTrack(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_LocalMediaTrackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_LocalMediaTrack');
  late final _rust_arc_increment_strong_count_RustOpaque_LocalMediaTrack =
      _rust_arc_increment_strong_count_RustOpaque_LocalMediaTrackPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_LocalMediaTrack(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_LocalMediaTrack(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_LocalMediaTrackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_LocalMediaTrack');
  late final _rust_arc_decrement_strong_count_RustOpaque_LocalMediaTrack =
      _rust_arc_decrement_strong_count_RustOpaque_LocalMediaTrackPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_MediaManagerHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_MediaManagerHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_MediaManagerHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_MediaManagerHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_MediaManagerHandle =
      _rust_arc_increment_strong_count_RustOpaque_MediaManagerHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_MediaManagerHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_MediaManagerHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_MediaManagerHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_MediaManagerHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_MediaManagerHandle =
      _rust_arc_decrement_strong_count_RustOpaque_MediaManagerHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_ReconnectHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_ReconnectHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_ReconnectHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_ReconnectHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_ReconnectHandle =
      _rust_arc_increment_strong_count_RustOpaque_ReconnectHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_ReconnectHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_ReconnectHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_ReconnectHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_ReconnectHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_ReconnectHandle =
      _rust_arc_decrement_strong_count_RustOpaque_ReconnectHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_RemoteMediaTrack(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_RemoteMediaTrack(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_RemoteMediaTrackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_RemoteMediaTrack');
  late final _rust_arc_increment_strong_count_RustOpaque_RemoteMediaTrack =
      _rust_arc_increment_strong_count_RustOpaque_RemoteMediaTrackPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_RemoteMediaTrack(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_RemoteMediaTrack(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_RemoteMediaTrackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_RemoteMediaTrack');
  late final _rust_arc_decrement_strong_count_RustOpaque_RemoteMediaTrack =
      _rust_arc_decrement_strong_count_RustOpaque_RemoteMediaTrackPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_RoomHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_RoomHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_RoomHandlePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
      'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_RoomHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_RoomHandle =
      _rust_arc_increment_strong_count_RustOpaque_RoomHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_RoomHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_RoomHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_RoomHandlePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
      'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_RoomHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_RoomHandle =
      _rust_arc_decrement_strong_count_RustOpaque_RoomHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
