// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

import 'api/dart/api.dart';
import 'api/dart/api/connection_handle.dart';
import 'api/dart/api/jason.dart';
import 'api/dart/api/local_media_track.dart';
import 'api/dart/api/media_manager.dart';
import 'api/dart/api/reconnect_handle.dart';
import 'api/dart/api/remote_media_track.dart';
import 'api/dart/api/room.dart';
import 'api/dart/api/room_close_reason.dart';
import 'frb_generated.dart';
import 'media.dart';
import 'media/constraints.dart';
import 'media/track.dart';
import 'media/track/remote.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ConnectionHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandlePtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_JasonPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJasonPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocalMediaTrackPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrackPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MediaManagerHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandlePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ReconnectHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandlePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RemoteMediaTrackPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrackPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RoomHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandlePtr;

  @protected
  ConnectionHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
    dynamic raw,
  );

  @protected
  Jason
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
    dynamic raw,
  );

  @protected
  LocalMediaTrack
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    dynamic raw,
  );

  @protected
  MediaManagerHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
    dynamic raw,
  );

  @protected
  ReconnectHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
    dynamic raw,
  );

  @protected
  RemoteMediaTrack
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
    dynamic raw,
  );

  @protected
  RoomHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
    dynamic raw,
  );

  @protected
  ConnectionHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
    dynamic raw,
  );

  @protected
  Jason
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
    dynamic raw,
  );

  @protected
  LocalMediaTrack
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    dynamic raw,
  );

  @protected
  MediaManagerHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
    dynamic raw,
  );

  @protected
  ReconnectHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
    dynamic raw,
  );

  @protected
  RemoteMediaTrack
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
    dynamic raw,
  );

  @protected
  RoomHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
    dynamic raw,
  );

  @protected
  int dco_decode_CastedPrimitive_usize(dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  ConnectionHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
    dynamic raw,
  );

  @protected
  Jason
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
    dynamic raw,
  );

  @protected
  LocalMediaTrack
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    dynamic raw,
  );

  @protected
  MediaManagerHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
    dynamic raw,
  );

  @protected
  ReconnectHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
    dynamic raw,
  );

  @protected
  RemoteMediaTrack
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
    dynamic raw,
  );

  @protected
  RoomHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ForeignClass dco_decode_TraitDef_ForeignClass(dynamic raw);

  @protected
  ApiAudioConstraints dco_decode_api_audio_constraints(dynamic raw);

  @protected
  ApiConstrainFacingMode dco_decode_api_constrain_facing_mode(dynamic raw);

  @protected
  ApiDeviceVideoTrackConstraints dco_decode_api_device_video_track_constraints(
    dynamic raw,
  );

  @protected
  ApiDisplayVideoTrackConstraints
  dco_decode_api_display_video_track_constraints(dynamic raw);

  @protected
  ApiMediaDeviceDetails dco_decode_api_media_device_details(dynamic raw);

  @protected
  ApiMediaDisplayDetails dco_decode_api_media_display_details(dynamic raw);

  @protected
  ApiMediaStreamSettings dco_decode_api_media_stream_settings(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ApiAudioConstraints dco_decode_box_autoadd_api_audio_constraints(dynamic raw);

  @protected
  ApiConstrainFacingMode dco_decode_box_autoadd_api_constrain_facing_mode(
    dynamic raw,
  );

  @protected
  ApiDeviceVideoTrackConstraints
  dco_decode_box_autoadd_api_device_video_track_constraints(dynamic raw);

  @protected
  ApiDisplayVideoTrackConstraints
  dco_decode_box_autoadd_api_display_video_track_constraints(dynamic raw);

  @protected
  ApiMediaStreamSettings dco_decode_box_autoadd_api_media_stream_settings(
    dynamic raw,
  );

  @protected
  ConstrainBoolean dco_decode_box_autoadd_constrain_boolean(dynamic raw);

  @protected
  ConstrainU32 dco_decode_box_autoadd_constrain_u_32(dynamic raw);

  @protected
  MediaSourceKind dco_decode_box_autoadd_media_source_kind(dynamic raw);

  @protected
  NoiseSuppressionLevel dco_decode_box_autoadd_noise_suppression_level(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ConstrainBoolean dco_decode_constrain_boolean(dynamic raw);

  @protected
  ConstrainU32 dco_decode_constrain_u_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FacingMode dco_decode_facing_mode(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<LocalMediaTrack>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    dynamic raw,
  );

  @protected
  List<ApiMediaDeviceDetails> dco_decode_list_api_media_device_details(
    dynamic raw,
  );

  @protected
  List<ApiMediaDisplayDetails> dco_decode_list_api_media_display_details(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MediaDeviceKind dco_decode_media_device_kind(dynamic raw);

  @protected
  MediaDirection dco_decode_media_direction(dynamic raw);

  @protected
  MediaKind dco_decode_media_kind(dynamic raw);

  @protected
  MediaSourceKind dco_decode_media_source_kind(dynamic raw);

  @protected
  NoiseSuppressionLevel dco_decode_noise_suppression_level(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ApiAudioConstraints? dco_decode_opt_box_autoadd_api_audio_constraints(
    dynamic raw,
  );

  @protected
  ApiConstrainFacingMode? dco_decode_opt_box_autoadd_api_constrain_facing_mode(
    dynamic raw,
  );

  @protected
  ApiDeviceVideoTrackConstraints?
  dco_decode_opt_box_autoadd_api_device_video_track_constraints(dynamic raw);

  @protected
  ApiDisplayVideoTrackConstraints?
  dco_decode_opt_box_autoadd_api_display_video_track_constraints(dynamic raw);

  @protected
  ConstrainBoolean? dco_decode_opt_box_autoadd_constrain_boolean(dynamic raw);

  @protected
  ConstrainU32? dco_decode_opt_box_autoadd_constrain_u_32(dynamic raw);

  @protected
  MediaSourceKind? dco_decode_opt_box_autoadd_media_source_kind(dynamic raw);

  @protected
  NoiseSuppressionLevel? dco_decode_opt_box_autoadd_noise_suppression_level(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  RoomCloseReason dco_decode_room_close_reason(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ConnectionHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
    SseDeserializer deserializer,
  );

  @protected
  Jason
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
    SseDeserializer deserializer,
  );

  @protected
  LocalMediaTrack
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    SseDeserializer deserializer,
  );

  @protected
  MediaManagerHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
    SseDeserializer deserializer,
  );

  @protected
  ReconnectHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
    SseDeserializer deserializer,
  );

  @protected
  RemoteMediaTrack
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
    SseDeserializer deserializer,
  );

  @protected
  RoomHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
    SseDeserializer deserializer,
  );

  @protected
  ConnectionHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
    SseDeserializer deserializer,
  );

  @protected
  Jason
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
    SseDeserializer deserializer,
  );

  @protected
  LocalMediaTrack
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    SseDeserializer deserializer,
  );

  @protected
  MediaManagerHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
    SseDeserializer deserializer,
  );

  @protected
  ReconnectHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
    SseDeserializer deserializer,
  );

  @protected
  RemoteMediaTrack
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
    SseDeserializer deserializer,
  );

  @protected
  RoomHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  ConnectionHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
    SseDeserializer deserializer,
  );

  @protected
  Jason
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
    SseDeserializer deserializer,
  );

  @protected
  LocalMediaTrack
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    SseDeserializer deserializer,
  );

  @protected
  MediaManagerHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
    SseDeserializer deserializer,
  );

  @protected
  ReconnectHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
    SseDeserializer deserializer,
  );

  @protected
  RemoteMediaTrack
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
    SseDeserializer deserializer,
  );

  @protected
  RoomHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApiAudioConstraints sse_decode_api_audio_constraints(
    SseDeserializer deserializer,
  );

  @protected
  ApiConstrainFacingMode sse_decode_api_constrain_facing_mode(
    SseDeserializer deserializer,
  );

  @protected
  ApiDeviceVideoTrackConstraints sse_decode_api_device_video_track_constraints(
    SseDeserializer deserializer,
  );

  @protected
  ApiDisplayVideoTrackConstraints
  sse_decode_api_display_video_track_constraints(SseDeserializer deserializer);

  @protected
  ApiMediaDeviceDetails sse_decode_api_media_device_details(
    SseDeserializer deserializer,
  );

  @protected
  ApiMediaDisplayDetails sse_decode_api_media_display_details(
    SseDeserializer deserializer,
  );

  @protected
  ApiMediaStreamSettings sse_decode_api_media_stream_settings(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ApiAudioConstraints sse_decode_box_autoadd_api_audio_constraints(
    SseDeserializer deserializer,
  );

  @protected
  ApiConstrainFacingMode sse_decode_box_autoadd_api_constrain_facing_mode(
    SseDeserializer deserializer,
  );

  @protected
  ApiDeviceVideoTrackConstraints
  sse_decode_box_autoadd_api_device_video_track_constraints(
    SseDeserializer deserializer,
  );

  @protected
  ApiDisplayVideoTrackConstraints
  sse_decode_box_autoadd_api_display_video_track_constraints(
    SseDeserializer deserializer,
  );

  @protected
  ApiMediaStreamSettings sse_decode_box_autoadd_api_media_stream_settings(
    SseDeserializer deserializer,
  );

  @protected
  ConstrainBoolean sse_decode_box_autoadd_constrain_boolean(
    SseDeserializer deserializer,
  );

  @protected
  ConstrainU32 sse_decode_box_autoadd_constrain_u_32(
    SseDeserializer deserializer,
  );

  @protected
  MediaSourceKind sse_decode_box_autoadd_media_source_kind(
    SseDeserializer deserializer,
  );

  @protected
  NoiseSuppressionLevel sse_decode_box_autoadd_noise_suppression_level(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ConstrainBoolean sse_decode_constrain_boolean(SseDeserializer deserializer);

  @protected
  ConstrainU32 sse_decode_constrain_u_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FacingMode sse_decode_facing_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<LocalMediaTrack>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiMediaDeviceDetails> sse_decode_list_api_media_device_details(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiMediaDisplayDetails> sse_decode_list_api_media_display_details(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MediaDeviceKind sse_decode_media_device_kind(SseDeserializer deserializer);

  @protected
  MediaDirection sse_decode_media_direction(SseDeserializer deserializer);

  @protected
  MediaKind sse_decode_media_kind(SseDeserializer deserializer);

  @protected
  MediaSourceKind sse_decode_media_source_kind(SseDeserializer deserializer);

  @protected
  NoiseSuppressionLevel sse_decode_noise_suppression_level(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ApiAudioConstraints? sse_decode_opt_box_autoadd_api_audio_constraints(
    SseDeserializer deserializer,
  );

  @protected
  ApiConstrainFacingMode? sse_decode_opt_box_autoadd_api_constrain_facing_mode(
    SseDeserializer deserializer,
  );

  @protected
  ApiDeviceVideoTrackConstraints?
  sse_decode_opt_box_autoadd_api_device_video_track_constraints(
    SseDeserializer deserializer,
  );

  @protected
  ApiDisplayVideoTrackConstraints?
  sse_decode_opt_box_autoadd_api_display_video_track_constraints(
    SseDeserializer deserializer,
  );

  @protected
  ConstrainBoolean? sse_decode_opt_box_autoadd_constrain_boolean(
    SseDeserializer deserializer,
  );

  @protected
  ConstrainU32? sse_decode_opt_box_autoadd_constrain_u_32(
    SseDeserializer deserializer,
  );

  @protected
  MediaSourceKind? sse_decode_opt_box_autoadd_media_source_kind(
    SseDeserializer deserializer,
  );

  @protected
  NoiseSuppressionLevel? sse_decode_opt_box_autoadd_noise_suppression_level(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  RoomCloseReason sse_decode_room_close_reason(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
    ConnectionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
    Jason self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    LocalMediaTrack self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
    MediaManagerHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
    ReconnectHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
    RemoteMediaTrack self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
    RoomHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
    ConnectionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
    Jason self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    LocalMediaTrack self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
    MediaManagerHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
    ReconnectHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
    RemoteMediaTrack self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
    RoomHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_usize(int self, SseSerializer serializer);

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
    ConnectionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
    Jason self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    LocalMediaTrack self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
    MediaManagerHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
    ReconnectHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
    RemoteMediaTrack self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
    RoomHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_api_audio_constraints(
    ApiAudioConstraints self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_constrain_facing_mode(
    ApiConstrainFacingMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_device_video_track_constraints(
    ApiDeviceVideoTrackConstraints self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_display_video_track_constraints(
    ApiDisplayVideoTrackConstraints self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_media_device_details(
    ApiMediaDeviceDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_media_display_details(
    ApiMediaDisplayDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_media_stream_settings(
    ApiMediaStreamSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_audio_constraints(
    ApiAudioConstraints self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_constrain_facing_mode(
    ApiConstrainFacingMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_device_video_track_constraints(
    ApiDeviceVideoTrackConstraints self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_display_video_track_constraints(
    ApiDisplayVideoTrackConstraints self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_media_stream_settings(
    ApiMediaStreamSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_constrain_boolean(
    ConstrainBoolean self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_constrain_u_32(
    ConstrainU32 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_media_source_kind(
    MediaSourceKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_noise_suppression_level(
    NoiseSuppressionLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_constrain_boolean(
    ConstrainBoolean self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_constrain_u_32(ConstrainU32 self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_facing_mode(FacingMode self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    List<LocalMediaTrack> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_media_device_details(
    List<ApiMediaDeviceDetails> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_media_display_details(
    List<ApiMediaDisplayDetails> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_device_kind(
    MediaDeviceKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_direction(
    MediaDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_kind(MediaKind self, SseSerializer serializer);

  @protected
  void sse_encode_media_source_kind(
    MediaSourceKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_noise_suppression_level(
    NoiseSuppressionLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_api_audio_constraints(
    ApiAudioConstraints? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_constrain_facing_mode(
    ApiConstrainFacingMode? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_device_video_track_constraints(
    ApiDeviceVideoTrackConstraints? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_display_video_track_constraints(
    ApiDisplayVideoTrackConstraints? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_constrain_boolean(
    ConstrainBoolean? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_constrain_u_32(
    ConstrainU32? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_media_source_kind(
    MediaSourceKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_noise_suppression_level(
    NoiseSuppressionLevel? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_room_close_reason(
    RoomCloseReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJasonPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJasonPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJasonPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJason =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJasonPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrackPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrack =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalMediaTrackPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaManagerHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconnectHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrackPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrack =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteMediaTrackPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_medea_jason_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
