// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'frb_generated.dart';

/// Audio device kind.
enum AudioDeviceKind {
  /// Built-in earpiece speaker.
  earSpeaker,

  /// Built-in loudspeaker.
  speakerphone,

  /// Wired headphones without microphone.
  wiredHeadphones,

  /// Wired headset with a microphone.
  wiredHeadset,

  /// USB headphones without microphone.
  usbHeadphones,

  /// USB headset with a microphone.
  usbHeadset,

  /// Bluetooth headphones profile (A2DP/BLE speaker).
  bluetoothHeadphones,

  /// Bluetooth headset profile suitable for calls (SCO/BLE headset).
  bluetoothHeadset,
}

/// [MediaDeviceInfo.kind][1] representation.
///
/// [1]: https://w3.org/TR/mediacapture-streams#dom-mediadeviceinfo-kind
enum MediaDeviceKind {
  /// Audio input device (for example, a microphone).
  audioInput,

  /// Video input device (for example, a webcam).
  videoInput,

  /// Audio output device (for example, a pair of headphones).
  audioOutput,
}

/// [MediaStreamTrack.kind][1] representation.
///
/// [1]: https://w3.org/TR/mediacapture-streams#dom-mediastreamtrack-kind
enum MediaKind {
  /// Audio track.
  audio,

  /// Video track.
  video,
}
