include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**.g.dart'
    - 'lib/src/native/ffi/frb/**'

linter:
  rules: # https://dart-lang.github.io/linter/lints/index.html
    prefer_single_quotes: true
