from ubuntu:latest
RUN apt update && apt install -y curl git cmake clang libgtk-3-dev liblzma-dev libpulse-dev ninja-build pkg-config xvfb

#Installing Flutter SDK
RUN git clone https://github.com/flutter/flutter.git
ENV PATH "$PATH:/flutter/bin"
RUN apt install unzip
RUN flutter channel dev
RUN flutter upgrade

COPY ./ ./pj
WORKDIR ./pj
CMD make do
