from ubuntu:latest
RUN apt update && apt install -y curl git cmake libgtk-3-dev liblzma-dev libpulse-dev ninja-build pkg-config xvfb

#Installing Flutter SDK
RUN git clone https://github.com/flutter/flutter.git
ENV PATH "$PATH:/flutter/bin"
RUN apt install unzip
RUN flutter channel dev
RUN flutter upgrade

COPY ./ ./pj
# CMD xvfb-run -a flutter drive --driver=test_driver/integration_test.dart --target=../test/e2e/suite.dart -d linux
