version: "2"

services:
  frontend:
    container_name: ${COMPOSE_PROJECT_NAME}-frontend
    image: nginx:stable-alpine
    #ports:
    #  - "30000:30000"    # frontend http
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ../pkg/:/usr/share/nginx/html/pkg/:ro
    network_mode: host
  webdriver:
    container_name: ${COMPOSE_PROJECT_NAME}-webdriver
    image: ${COMPOSE_WEBDRIVER_IMAGE_NAME}:${COMPOSE_WEBDRIVER_IMAGE_VER}
    depends_on: ["frontend"]
    #ports:
    #  - "4444:4444"      # browser webdriver
    entrypoint: ${COMPOSE_WEBDRIVER_ENTRYPOINT}
    shm_size: 512m
    network_mode: host
