{
 "title": "First ever",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "label": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Rooms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rooms" }
   ]
  },
  {
   "title": "Members",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "members" }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "peers" },
    {
     "expr": "peers{mode=\"sfu\"}"
    },
    {
     "expr": "peers{mode=\"mesh\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}