# Additional labels to apply to all Kubernetes resources created by this chart.
labels: {}
  # app.kubernetes.io/part-of: frontend

server:
  image:
    repository: hub.instrumentisto.com/streaming/medea
    tag: 0.2.0
    pullPolicy: IfNotPresent

  # Medea media server configuration:
  # https://github.com/instrumentisto/medea/blob/master/config.toml
  conf:
    server:
      client:
        http:
          public_url: ws://127.0.0.1:8080/ws
          bind_port: 8080
      control:
        grpc:
          bind_port: 6565

    ice:
      embedded:
        # IP address to be used by Turn as relay.
        # If empty then `status.hostIP` of Pod will be used.
        public_host: ""

  deployment:
    revisionHistoryLimit: 0

    # Optional revision number that may used for fine-grained Deployment rollouts.
    revision: ""

    annotations: {}
      # kubernetes.io/change-cause=kubectl set ...

    affinity: {}
      # nodeAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: node-label-key
      #           operator: In
      #           values: ["node-label-value"]

    tolerations: []
      # - key: "node.alpha.kubernetes.io/unreachable"
      #   operator: "Exists"
      #   effect: "NoExecute"

    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

  control-mock:
    image:
      repository: ghcr.io/instrumentisto/medea-control-api-mock
      tag: 0.2.0
      pullPolicy: IfNotPresent

    # Medea's Control API mock server configuration.
    conf:
      bind_port: 8000
      log:
        level: DEBUG

web-client:
  image:
    repository: ghcr.io/instrumentisto/medea-demo
    tag: 0.1.0
    pullPolicy: IfNotPresent

  conf:
    # Optional custom Nginx vhost configuration.
    nginx: ""
    # nginx: |
    #   server {
    #     listen         80 default_server;
    #     ...

  deployment:
    replicas: 1
    revisionHistoryLimit: 0

    # Optional revision number that may used for fine-grained Deployment rollouts.
    revision: ""

    annotations: {}
      # kubernetes.io/change-cause=kubectl set ...

    affinity: {}
      # nodeAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: node-label-key
      #           operator: In
      #           values: ["node-label-value"]

    tolerations: []
      # - key: "node.alpha.kubernetes.io/unreachable"
      #   operator: "Exists"
      #   effect: "NoExecute"

    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi


ingress:
  enabled: yes

  hosts:
    - medea-demo.test

  tls:
    enabled: yes
    auto: no
    # Not required when "auto" is enabled.
    secretName:
      medea-demo.test: medea-demo.test.tls

  annotations:
    kubernetes.io/ingress.class: nginx
