#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.49.0.

use crate::api::dart::jason_api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::sync::Mutex;
use std::sync::RwLock;

// Section: imports

// Section: wire functions

fn wire_jason_new_impl() -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "jason_new",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || Ok(jason_new()),
    )
}
fn wire_jason_init_room_impl(
    jason: impl Wire2Api<Opaque<Jason>> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "jason_init_room",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_jason = jason.wire2api();
            Ok(jason_init_room(api_jason))
        },
    )
}
fn wire_jason_media_manager_impl(
    jason: impl Wire2Api<Opaque<Jason>> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "jason_media_manager",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_jason = jason.wire2api();
            Ok(jason_media_manager(api_jason))
        },
    )
}
fn wire_jason_close_room_impl(
    jason: impl Wire2Api<Opaque<Jason>> + UnwindSafe,
    room_to_delete: impl Wire2Api<Opaque<RoomHandle>> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "jason_close_room",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_jason = jason.wire2api();
            let api_room_to_delete = room_to_delete.wire2api();
            Ok(jason_close_room(api_jason, api_room_to_delete))
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: deallocate functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "jason_api_g.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
