#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.49.0.

use crate::api::dart::media_manager_handle_api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::sync::Mutex;
use std::sync::RwLock;

// Section: imports

// Section: wire functions

fn wire_media_manager_handle_init_local_tracks_impl(
    manager: impl Wire2Api<Opaque<MediaManagerHandle>> + UnwindSafe,
    caps: impl Wire2Api<Opaque<MediaStreamSettings>> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "media_manager_handle_init_local_tracks",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_manager = manager.wire2api();
            let api_caps = caps.wire2api();
            Ok(media_manager_handle_init_local_tracks(
                api_manager,
                api_caps,
            ))
        },
    )
}
fn wire_media_manager_handle_enumerate_devices_impl(
    manager: impl Wire2Api<Opaque<MediaManagerHandle>> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "media_manager_handle_enumerate_devices",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_manager = manager.wire2api();
            Ok(media_manager_handle_enumerate_devices(api_manager))
        },
    )
}
fn wire_media_manager_handle_enumerate_displays_impl(
    manager: impl Wire2Api<Opaque<MediaManagerHandle>> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "media_manager_handle_enumerate_displays",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_manager = manager.wire2api();
            Ok(media_manager_handle_enumerate_displays(api_manager))
        },
    )
}
fn wire_media_manager_handle_set_output_audio_id_impl(
    manager: impl Wire2Api<Opaque<MediaManagerHandle>> + UnwindSafe,
    device_id: impl Wire2Api<String> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "media_manager_handle_set_output_audio_id",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_manager = manager.wire2api();
            let api_device_id = device_id.wire2api();
            Ok(media_manager_handle_set_output_audio_id(
                api_manager,
                api_device_id,
            ))
        },
    )
}
fn wire_media_manager_handle_set_microphone_volume_impl(
    manager: impl Wire2Api<Opaque<MediaManagerHandle>> + UnwindSafe,
    level: impl Wire2Api<i64> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "media_manager_handle_set_microphone_volume",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_manager = manager.wire2api();
            let api_level = level.wire2api();
            Ok(media_manager_handle_set_microphone_volume(
                api_manager,
                api_level,
            ))
        },
    )
}
fn wire_media_manager_handle_microphone_volume_is_available_impl(
    manager: impl Wire2Api<Opaque<MediaManagerHandle>> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "media_manager_handle_microphone_volume_is_available",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_manager = manager.wire2api();
            Ok(media_manager_handle_microphone_volume_is_available(
                api_manager,
            ))
        },
    )
}
fn wire_media_manager_handle_microphone_volume_impl(
    manager: impl Wire2Api<Opaque<MediaManagerHandle>> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "media_manager_handle_microphone_volume",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_manager = manager.wire2api();
            Ok(media_manager_handle_microphone_volume(api_manager))
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: deallocate functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<i64> for i64 {
    fn wire2api(self) -> i64 {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "media_manager_handle_api_g.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
