#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.49.0.

use crate::api::dart::reconnect_handle_api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::sync::Mutex;
use std::sync::RwLock;

// Section: imports

// Section: wire functions

fn wire_reconnect_handle_reconnect_with_delay_impl(
    reconnect_handle: impl Wire2Api<Opaque<ReconnectHandle>> + UnwindSafe,
    delay_ms: impl Wire2Api<i64> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "reconnect_handle_reconnect_with_delay",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_reconnect_handle = reconnect_handle.wire2api();
            let api_delay_ms = delay_ms.wire2api();
            Ok(reconnect_handle_reconnect_with_delay(
                api_reconnect_handle,
                api_delay_ms,
            ))
        },
    )
}
fn wire_reconnect_handle_reconnect_with_backoff_impl(
    reconnect_handle: impl Wire2Api<Opaque<ReconnectHandle>> + UnwindSafe,
    starting_delay: impl Wire2Api<i64> + UnwindSafe,
    multiplier: impl Wire2Api<f64> + UnwindSafe,
    max_delay: impl Wire2Api<u32> + UnwindSafe,
    max_elapsed_time_ms: impl Wire2Api<Option<u32>> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "reconnect_handle_reconnect_with_backoff",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_reconnect_handle = reconnect_handle.wire2api();
            let api_starting_delay = starting_delay.wire2api();
            let api_multiplier = multiplier.wire2api();
            let api_max_delay = max_delay.wire2api();
            let api_max_elapsed_time_ms = max_elapsed_time_ms.wire2api();
            Ok(reconnect_handle_reconnect_with_backoff(
                api_reconnect_handle,
                api_starting_delay,
                api_multiplier,
                api_max_delay,
                api_max_elapsed_time_ms,
            ))
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: deallocate functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u32> for *mut u32 {
    fn wire2api(self) -> u32 {
        unsafe { *support::box_from_leak_ptr(self) }
    }
}
impl Wire2Api<f64> for f64 {
    fn wire2api(self) -> f64 {
        self
    }
}
impl Wire2Api<i64> for i64 {
    fn wire2api(self) -> i64 {
        self
    }
}

impl Wire2Api<u32> for u32 {
    fn wire2api(self) -> u32 {
        self
    }
}
// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "reconnect_handle_api_g.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
