#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.49.0.

use crate::api::dart::room_close_reason_api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::sync::Mutex;
use std::sync::RwLock;

// Section: imports

// Section: wire functions

fn wire_room_close_reason_reason_impl(
    room_close_reason: impl Wire2Api<Opaque<RoomCloseReason>> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "room_close_reason_reason",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_room_close_reason = room_close_reason.wire2api();
            Ok(room_close_reason_reason(api_room_close_reason))
        },
    )
}
fn wire_room_close_reason_is_closed_by_server_impl(
    room_close_reason: impl Wire2Api<Opaque<RoomCloseReason>> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "room_close_reason_is_closed_by_server",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_room_close_reason = room_close_reason.wire2api();
            Ok(room_close_reason_is_closed_by_server(api_room_close_reason))
        },
    )
}
fn wire_room_close_reason_is_err_impl(
    room_close_reason: impl Wire2Api<Opaque<RoomCloseReason>> + UnwindSafe,
) -> support::WireSyncReturnStruct {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "room_close_reason_is_err",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_room_close_reason = room_close_reason.wire2api();
            Ok(room_close_reason_is_err(api_room_close_reason))
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: deallocate functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "room_close_reason_api_g.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
