// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../../frb_generated.dart';
import '../../../media/track.dart';
import '../api.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnectionHandle>>
abstract class ConnectionHandle implements RustOpaqueInterface, ForeignClass {
  /// Disables inbound audio in the associated [`Connection`].
  Object disableRemoteAudio();

  /// Disables inbound video in the associated [`Connection`].
  ///
  /// Affects only video with the provided [`MediaSourceKind`], if any.
  Object disableRemoteVideo({MediaSourceKind? sourceKind});

  /// Enables inbound audio in the associated [`Connection`].
  Object enableRemoteAudio();

  /// Enables inbound video in the associated [`Connection`].
  ///
  /// Affects only video with the provided [`MediaSourceKind`], if any.
  Object enableRemoteVideo({MediaSourceKind? sourceKind});

  /// Constructs a [`ForeignClass`] from the given raw pointer via
  /// [`Box::from_raw()`].
  ///
  /// # Safety
  ///
  /// Same as for [`Box::from_raw()`].
  static ConnectionHandle fromPtr({required int ptr}) => RustLib.instance.api
      .crateApiDartApiConnectionHandleConnectionHandleFromPtr(ptr: ptr);

  /// Returns ID of remote `Member` ID of the associated [`Connection`].
  ///
  /// # Errors
  ///
  /// If the [`core::ConnectionHandle::get_remote_member_id()`] method errors.
  String getRemoteMemberId();

  /// Sets a callback to be invoked once the associated [`Connection`] is
  /// closed.
  ///
  /// # Errors
  ///
  /// If the [`core::ConnectionHandle::on_close()`] method errors.
  void onClose({required Object f});

  /// Sets a callback to be invoked once a quality score of the associated
  /// [`Connection`] is updated by a media server.
  ///
  /// # Errors
  ///
  /// If the [`core::ConnectionHandle::on_quality_score_update()`] method
  /// errors.
  void onQualityScoreUpdate({required Object f});

  /// Sets a callback to be invoked once a new [`remote::Track`] is added to
  /// the associated [`Connection`].
  ///
  /// # Errors
  ///
  /// If the [`core::ConnectionHandle::on_remote_track_added()`] method
  /// errors.
  ///
  /// [`remote::Track`]: media::track::remote::Track
  void onRemoteTrackAdded({required Object f});
}
