// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../../frb_generated.dart';
import '../../../media.dart';
import '../../../media/track.dart';
import '../../dart.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `from`

/// Returns the [`Vec<LocalMediaTrack>`] from the
/// [`ForeignClass`] address.
List<LocalMediaTrack> vecLocalTracksFromRaw({required int ptr}) =>
    RustLib.instance.api
        .crateApiDartApiLocalMediaTrackVecLocalTracksFromRaw(ptr: ptr);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LocalMediaTrack>>
abstract class LocalMediaTrack implements RustOpaqueInterface, ForeignClass {
  /// Frees the data behind the provided opaque local track.
  Object free();

  /// Returns the [`LocalMediaTrack`] from the [`ForeignClass`] address.
  static LocalMediaTrack fromRaw({required int ptr}) => RustLib.instance.api
      .crateApiDartApiLocalMediaTrackLocalMediaTrackFromRaw(ptr: ptr);

  /// Returns a [`Dart_Handle`] to the underlying [`MediaStreamTrack`] of the
  /// provided [`LocalMediaTrack`].
  ///
  /// [`MediaStreamTrack`]: platform::MediaStreamTrack
  Object getTrack();

  /// Indicates whether an `OnAudioLevelChangedCallback` is supported for this
  /// [`LocalMediaTrack`].
  bool isOnAudioLevelAvailable();

  /// Returns a [`MediaKind::Audio`] if the provided [`LocalMediaTrack`]
  /// represents an audio track, or a [`MediaKind::Video`] if it represents a
  /// video track.
  MediaKind kind();

  /// Returns a [`MediaSourceKind::Device`] if the provided
  /// [`LocalMediaTrack`] is sourced from some device
  /// (webcam/microphone), or a [`MediaSourceKind::Display`] if it's
  /// captured via [MediaDevices.getDisplayMedia()][1].
  ///
  /// [1]: https://w3.org/TR/screen-capture#dom-mediadevices-getdisplaymedia
  MediaSourceKind mediaSourceKind();

  /// Sets the provided `OnAudioLevelChangedCallback` for this
  /// [`LocalMediaTrack`].
  ///
  /// It's called for live [`LocalMediaTrack`]s when their audio level
  /// changes.
  void onAudioLevelChanged({required Object f});

  /// Sets callback to invoke when this [`LocalMediaTrack`] is ended.
  void onEnded({required Object f});

  /// Returns a [`media::MediaStreamTrackState::Live`] if this
  /// [`LocalMediaTrack`] is active, or a
  /// [`media::MediaStreamTrackState::Ended`] if it has ended.
  Object state();
}
